# Generated by Django 4.2.1 on 2023-06-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='card_number',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='cardholder_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='cvv',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='mail',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='phone',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='surname',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='validity',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
